{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "iap.fullname" . }}-ingress
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "ingress"
  annotations:
    kubernetes.io/description: "Itential Automation Platform Ingress. Contains load balanced access and individual access"
    {{- include "iap.annotations" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  # Load balanced access
  {{- if .Values.ingress.loadBalancer.enabled }}
  - host: {{ .Values.ingress.loadBalancer.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "iap.fullname" . }}-service
            port:
              number: {{ .Values.service.port }}
        path: {{ .Values.ingress.loadBalancer.path | default "/" }}
        pathType: {{ .Values.ingress.pathType | default "Prefix" }}
      {{- if .Values.useWebSockets }}
      - backend:
          service:
            name: {{ include "iap.fullname" . }}-service
            port:
              number: {{ .Values.websocketPort }}
        path: "/ws"
        pathType: "Prefix"
      {{- end }}
  {{- end }}
  # Direct access
  {{- if .Values.ingress.directAccess.enabled }}
  {{- range $i := until (.Values.replicaCount | int) }}
  - host: {{ printf "%s-%s-%d.%s" (include "iap.name" $) $.Release.Namespace $i $.Values.ingress.directAccess.baseDomain | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "iap.fullname" $ }}-service-headless-{{ $i }}
            port:
              number: {{ $.Values.service.port }}
        path: {{ $.Values.ingress.directAccess.path | default "/" }}
        pathType: {{ $.Values.ingress.pathType | default "Prefix" }}
  {{- end }}
  {{- end }}
{{- end }}
