{{- range $i := until (.Values.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.service.name }}-headless-{{ $i }}
  labels:
    {{- include "iap.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "service"
  annotations:
    kubernetes.io/description: "Itential Automation Platform headless service to individual pods."
    {{- include "iap.annotations" $ | nindent 4 }}
    {{- with $.Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "iap.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "iap.fullname" $ }}-{{ $i }}
  ports:
    - name: https
      port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.applicationPort }}
      protocol: TCP
    {{- if and $.Values.processExporter $.Values.processExporter.enabled }}
    - name: process-metrics
      port: 9256
      targetPort: 9256
      protocol: TCP
    {{- end }}
{{- end }}