---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "service"
  annotations:
    kubernetes.io/description: "Itential Automation Platform load balanced service."
    {{- include "iap.annotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.applicationPort }}
      protocol: TCP
    {{- if .Values.useWebSockets }}
    - name: ws
      port: {{ .Values.websocketPort }}
      targetPort: {{ .Values.websocketPort }}
      protocol: TCP
    {{- end }}
    {{- if and .Values.processExporter .Values.processExporter.enabled }}
    - name: process-metrics
      port: 9256
      targetPort: 9256
      protocol: TCP
    {{- end }}
  selector:
    {{- include "iap.selectorLabels" . | nindent 4 }}
