{{- if .Values.storageClass.enabled -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "storageclass"
  annotations:
    kubernetes.io/description: "Itential Automation Platform StorageClass used for persistent volumes."
    {{- include "iap.annotations" . | nindent 4 }}
    {{- with .Values.storageClass.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  {{- toYaml .Values.storageClass.parameters | nindent 2 }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end }}